# 多环境通用配置，不能放其他内容？？TODO
spring:
  application:
    name: first-eureka-provider
  profiles:
    active: ${profiles.active}


---
server:
  port: 8848
eureka:
  instance:
    # 该服务的主机名称
    hostname: localhost
  client:
    # 服务器端调用健康检查处理器 getStatus() 方法的时间间隔，默认时间间隔 30s
    #instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/

spring:
  profiles: dev_01

person:
  name: 来自dev_01
  age: 100


---
server:
  port: 8849

eureka:
  instance:
    hostname: localhost
  client:
    #instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/

spring:
  profiles: dev_02

person:
  name: 来自dev_02
  age: 1000