spring:
  application:
    name: eureka-customer

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/ #,http://localhost:8762/eureka/
    enabled: false

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false