spring:
  application:
    name: eureka-customer

# Spring Boot Common application properties（https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html）
server:
  port: 8081
##  connection-timeout:
#  tomcat:
#    max-threads: 10
#    max-connections: 10
#    accept-count: 10

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/ #,http://localhost:8762/eureka/
    enabled: false

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false

