spring:
  application:
    name: first-eureka-customer

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false