spring:
  application:
    name: provider
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/for_learn?characterEncoding=utf-8&useSSL=false
      username: root
      password: JrhtNvP2y73AMHzKnwssJNjP45oqwz9lBgvGivkhMHpuyj3obx5pSdCctR2po1+dF3KoXhpCE1H001UNOjbzyA==
      initial-size: 5 #初始化时，建立物理连接个数
      max-active: 5
      min-idle: 5
      filters: config,stat,slf4j
      connection-properties: config.decrypt=true;config.decrypt.key=${publickey} #https://github.com/alibaba/druid/wiki/%E4%BD%BF%E7%94%A8ConfigFilter

publickey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALIaSVy3V5r1w+LXNz/nwFwXYZq4O+44Cxs7UZnPuihK+/Tp6CHgFizrJuTsijX0xSn/I9vHbsh5h8vD/IZIh2ECAwEAAQ==

mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*" # 默认值是 true，敏感端口不对外暴露，默认情况下这个只显示服务是否启动（UP），其他 HealthIndicator（discoveryComposite、diskSpace 等） 信息不输出

eureka:
  instance:
#     preferIpAddress: true #http://www.itmuch.com/spring-cloud-code-read/spring-cloud-code-read-eureka-registry-ip/ TODO
    # 该服务的主机名称
      hostname: localhost
  client:
#    healthcheck:
#      enabled: true
    # 服务器端调用健康检查处理器 getStatus() 方法的时间间隔，默认时间间隔 30s
#    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl: #
      defaultZone: http://localhost:9090/eureka/ #,http://localhost:8762/eureka/
    enabled: false #不使用 Eureka Server

server:
  port: 8080

logging:
  level:
    com.hystrix: INFO
